version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: movies_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MoviesDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: movies_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@movies.com
      PGADMIN_DEFAULT_PASSWORD: admin
      NEXT_PUBLIC_API_URL: "https://backend:5001"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movies_api
    restart: always
    ports:
    - "8080:8080"   # HTTP
    - "5001:5001"   # HTTPS
    depends_on:
    - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=MoviesDb;Username=postgres;Password=postgres"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /root/.aspnet/https/moviesapi.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: Birukdjn@8325
    volumes:
    - ./backend:/app
    - /app/bin
    - ~/.aspnet/https:/root/.aspnet/https:ro
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movies_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
